#!/bin/bash
set -e

# Configuration from environment variables (with defaults)
BITCOIN_RPC_PORT=${BITCOIN_RPC_PORT:-8332}
BITCOIN_P2P_PORT=${BITCOIN_P2P_PORT:-8333}
LND_GRPC_PORT=${LND_GRPC_PORT:-10009}
LND_REST_PORT=${LND_REST_PORT:-8080}
ELECTRS_PORT=${ELECTRS_PORT:-50001}

# Static IPs for services (must match docker-compose network config)
BITCOIND_IP=${BITCOIND_IP:-172.28.0.3}
LND_IP=${LND_IP:-172.28.0.4}
ELECTRS_IP=${ELECTRS_IP:-172.28.0.5}

# Generate torrc configuration
generate_torrc() {
    cat > /etc/tor/torrc << EOF
# =============================================================================
# Tor Configuration - Auto-generated by entrypoint.sh
# =============================================================================

# Data directory
DataDirectory /var/lib/tor

# SOCKS proxy (for Bitcoin and LND to route traffic through Tor)
SocksPort 0.0.0.0:9050

# Control port (for LND to create hidden services)
ControlPort 0.0.0.0:9051
CookieAuthentication 1
CookieAuthFile /var/lib/tor/control_auth_cookie
CookieAuthFileGroupReadable 1

# -----------------------------------------------------------------------------
# Hidden Services
# -----------------------------------------------------------------------------

# Bitcoin RPC Hidden Service (for remote wallet connections like Sparrow)
HiddenServiceDir /var/lib/tor/bitcoin_rpc
HiddenServiceVersion 3
HiddenServicePort ${BITCOIN_RPC_PORT} ${BITCOIND_IP}:${BITCOIN_RPC_PORT}

# Bitcoin P2P Hidden Service (for bitnodes.io visibility and peer connections)
HiddenServiceDir /var/lib/tor/bitcoin_p2p
HiddenServiceVersion 3
HiddenServicePort ${BITCOIN_P2P_PORT} ${BITCOIND_IP}:${BITCOIN_P2P_PORT}

# LND gRPC Hidden Service (for advanced wallet apps)
HiddenServiceDir /var/lib/tor/lnd_grpc
HiddenServiceVersion 3
HiddenServicePort ${LND_GRPC_PORT} ${LND_IP}:${LND_GRPC_PORT}

# LND REST Hidden Service (for mobile wallets like Zeus)
HiddenServiceDir /var/lib/tor/lnd_rest
HiddenServiceVersion 3
HiddenServicePort ${LND_REST_PORT} ${LND_IP}:${LND_REST_PORT}

# Electrs Hidden Service (for Sparrow and other Electrum-compatible wallets)
HiddenServiceDir /var/lib/tor/electrs
HiddenServiceVersion 3
HiddenServicePort ${ELECTRS_PORT} ${ELECTRS_IP}:${ELECTRS_PORT}

# -----------------------------------------------------------------------------
# Performance & Security
# -----------------------------------------------------------------------------

# Logging
Log notice stdout

# Disable exit relay functionality (we're only a client)
ExitRelay 0
EOF
}

# Create hidden service directories with proper permissions
setup_hidden_services() {
    for dir in bitcoin_rpc bitcoin_p2p lnd_grpc lnd_rest electrs; do
        mkdir -p "/var/lib/tor/${dir}"
        chown tor:tor "/var/lib/tor/${dir}"
        chmod 700 "/var/lib/tor/${dir}"
    done
}

# Main execution
if [ "$(id -u)" = "0" ]; then
    echo "Setting up Tor configuration..."

    # Generate configuration
    generate_torrc

    # Setup directories
    setup_hidden_services

    # Fix ownership
    chown -R tor:tor /var/lib/tor /var/log/tor /run/tor

    echo "Starting Tor as tor user..."
    exec gosu tor tor -f /etc/tor/torrc
else
    exec tor -f /etc/tor/torrc
fi
